// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PageAsideLeft: typeof import('./src/components/PageLayout/PageAsideLeft/src/PageAsideLeft.vue')['default']
    PageAsideRight: typeof import('./src/components/PageLayout/PageAsideRight/src/PageAsideRight.vue')['default']
    PageHeader: typeof import('./src/components/PageLayout/PageHeader/src/PageHeader.vue')['default']
    PageMain: typeof import('./src/components/PageLayout/PageMain/src/PageMain.vue')['default']
  }
}

export { }
